// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import ()

type PdfText struct {
	Filepath          string
	Page              int64
	SearchableContent string
	OriginalContent   string
	DateCreated       string
}
